[package]
authors = ["Stefan Kewatt <stefan.kewatt@gmail.com>"]
edition = "2018"
name = "lib6502"
version = "0.0.1-alpha"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitfield = "0.13.2"
futures = "0.3"
paste = "1.0"
